services:
  # 1. Your Python Service
  grading-service:
    build: .
    container_name: ielts-grader
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db  # Wait for DB to start
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # 2. The New Database Service
  db:
    image: postgres:18-alpine
    container_name: ielts-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ielts_grading_db
    ports:
      - "5432:5432" # Expose port if you want to inspect it with a GUI tool
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: