version: '1.0'

services:
  test_db:
    image: mongo
    container_name: test_db
    port:
      - "27018:27017"
    volumes:
      - mongo-data:/data/test_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet 
      interval: 10s
      timeout: 30s
      retries: 5
    network:
      - app_network
  
  test_service:
    build: ./test-service
    container_name: test_service
    port: "8000:8000"
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - ./test-service:/app
    network:
      - app_network


volumes:
  mongo_data:

network:
  app_network:
    driver: bridge
