spring.datasource.url=jdbc:mysql://localhost:3306/submit
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

USER_SERVICE_URL=http://26.78.195.142:8081/userservice/api/user/
TEST_SERVICE_URL=http://26.78.195.142:8000/api/test/

# server.address=0.0.0.0
# server.port=8080
# 26.78.195.142
# 26.210.159.83
# 26.131.227.3


